name: Build and Push Docker Image

on:
  push:
    branches:
      - devcontainer # Solo se ejecutará cuando hagas push a la rama "devcontainer"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DockerHubSQL # Especifica el entorno aquí

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME  }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/leumag-backend-sqlserver:v1 .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/leumag-backend-sqlserver:v1
